/control/verbose 1
/run/numberOfThreads 1
/vis/disable

# physics/cuts (set before initialize)
# fine step limiter for dE/dx and small production cuts
/process/eLoss/StepFunction 0.0001 0.001 mm
/run/setCut 1 um

/run/initialize

# fire the events
/run/verbose 1

/B3/primary/spectrumFile ../spectra/CXB_gamma.txt
/B3/primary/particle gamma
/B3/primary/emissionMode sphere
/B3/primary/sphereRadius 30

/run/beamOn 100000